### ISSUE TITLE
Talk about bugs in the development section

### ISSUE THREAD

**Issue by oriolbcn** [MarsBased/handbook#41]
* What to do when you find a bug (fix it if it is very easy or very critical, otherwise open a new issue)
* Commuinicate
* Determine if it has an impact in production
* Prioritize

**Comment by xredo** [comment]
Some considerations about this suggestion.

My opinion is that this falls more in the "common sense" side than in the "we need to create a procedure for that". It will highly depend on a lot of different factors, the kind of project, the people involved in the project and the situation.

For example,  If the bug is a big security issue and the application is deployed to production with sensitive data the developer will alert the tech lead who will alert the MarsBased CTO. And all together we'll discuss why it happened, what can be done and the best way to communicate this to avoid unnecessary panic. I don't see any other path of action.

What we need to encourage is to communicate more and more often. Because when you communicate things you normally take the best decision. And no procedure can beat that. I prefer procedures and guides for those things that will always remain the same, independent of the context.

If we want to enforce this more at MarsBased we can speak more about it in our company meetings. To have it on top of our minds. But focusing on the communication part.

**Comment by oriolbcn** [comment]
Yep those are very good insights thanks Xavi! Let's not write a guide for this now. If later we have a suggesstion with more specific content we can discuss it again.
