### ISSUE TITLE
Class structure

### ISSUE THREAD

**Issue by fernandomeridamatilla** [MarsBased/handbook#46]
Although there is a rule in the marstyle eslint for creating an angular component class; 
it is an important part of development and I think it would be good to include an example in the guide

- Class order
  1. Inputs/Outputs
  2. ViewChilds
  3. Public variables
  4. Private variables
  5. Get methods
  6. Constructor
  7. Lifecycle Hooks
  8. Callback methods
  9. Public methods
  10. Private methods
  
```ts
const MY_LIST = [{id: 1, value: 'option 1'}, {id: 2, value: 'option 2'}]

export class MyComponent {
  @Input() categories: Category[];

  @Output() disassociate = new EventEmitter<Category>();

  @ViewChild(FormComponent) formCpm: FormComponent;

  user: User;
  category: Category;
  private selectedUser: User;
  private selectedCategory: Category;
  readonly comboList = MY_LIST;

  get isActive(): boolean {
    return this.user.active;
  }

  get isSectionVisible(): boolean {
    return !!this.user;
  }

  constructor() { }

  ngOnInit(): void {
    this.initData();
  }

  ngOnDestroy(): void {
    this.freeResources();
  }

  onClickUser(): void {
    ...
  }

  onChangeDate(): void {
    ...
  }

  submit(): void {
    ...
  }

  private initData(): void {
    ...
  }

  private freeResources(): void {
    ...
  }
}
```

**Comment by davidgg** [comment]
Hi @fernandomeridamatilla, first, thanks for your suggestion.

Indeed, it's an important concept. I'd like to add something like this, but we'll have to find a good way. Before, talking about that, check the next concerns I have:

- Since we're adding an Angular component, add the component's decorator.
- Accessors (gets and sets) ordering is not defined inside the ESLint file, but I don't sure about the way you did it. I'll open a different issue to address this, so no worry about it for now.

About adding this, make a suggestion and a PR. What about adding a new DO? _Do order class members_ enumerate the order and add this. But keep it shorter, remove  `isSectionVisible`, `ngOnDestroy`, `onClickUser`,  `onChangeDate`,  `freeResources`. In case you want to state rules about extra concepts (event names or whatever) we should address them in a different issue/PR.
